// examples/vite-react/src/Switcher.tsx
import type { ReactElement } from 'react'
import { useLocale } from 'loclizr/react'
import * as m from './loclizr/messages'

const offered = [m.sourceLocale, ...m.locales.filter((tag) => tag !== m.sourceLocale)]

export function Switcher(): ReactElement {
  const locale = useLocale()
  const names = new Intl.DisplayNames([locale], { type: 'language' })
  return (
    <div className="switcher">
      <span className="label" id="switcher-label">
        {m.app_language()}
      </span>
      <div className="switcher__set" role="group" aria-labelledby="switcher-label">
        {offered.map((tag) => (
          <button
            key={tag}
            type="button"
            className={tag === locale ? 'switcher__tag switcher__tag--on' : 'switcher__tag'}
            aria-pressed={tag === locale}
            onClick={() => m.setLocale(tag)}
          >
            {names.of(tag) ?? tag}
          </button>
        ))}
      </div>
    </div>
  )
}

// examples/solid/src/Switcher.tsx
import { For } from 'solid-js'
import { createLocale } from './locale'
import * as m from './loclizr/messages'

export function Switcher() {
  const locale = createLocale()
  return (
    <div>
      <For each={m.locales}>
        {(tag) => (
          <button type="button" aria-pressed={tag === locale()} onClick={() => m.setLocale(tag)}>
            {tag}
          </button>
        )}
      </For>
    </div>
  )
}
